// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3IJD7NMxlAIgDdrCj5f5qcpCgu1ZJUuM',
    appId: '1:1026498125809:web:198f70f1ccd84d4159ae50',
    messagingSenderId: '1026498125809',
    projectId: 'flutter-chat-eadd2',
    authDomain: 'flutter-chat-eadd2.firebaseapp.com',
    storageBucket: 'flutter-chat-eadd2.appspot.com',
    measurementId: 'G-RJXFQ3NG7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo9N7QYDLxd-L6t-qouvt3owmIF5gUALw',
    appId: '1:1026498125809:android:467b37befa124bbf59ae50',
    messagingSenderId: '1026498125809',
    projectId: 'flutter-chat-eadd2',
    storageBucket: 'flutter-chat-eadd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChUl1kG8ltmRTkqxkPRN8dXsNXRmT7qJc',
    appId: '1:1026498125809:ios:547670a7847c5deb59ae50',
    messagingSenderId: '1026498125809',
    projectId: 'flutter-chat-eadd2',
    storageBucket: 'flutter-chat-eadd2.appspot.com',
    iosClientId: '1026498125809-ckg2fk4kqfce9nrvn376jc0a8cp1qgk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
